### ISSUE TITLE
Enemy AI

### ISSUE THREAD

**Issue by tripledubs** [sharris40/RocketDog#5]

**Comment by sharris40** [comment]
My current plan is to use Decorators in combination with State patterns. Each object on screen is an Entity, and an Entity is decorated with a MovementController package that determines how the object moves. The player will be an Entity with the (unique) PlayerController object; enemies would have an AIController attached; barrels could have both a CarryableObjectController and RollableController; etc. 

Each MovementController will have its own set of movement states that it cycles between. For instance, an AIController would start in the Roaming state. If an enemy is spotted, it will move to an Approaching state until it gets into range. Once in range, the enemy would go into the Attacking state. If the enemy moves out of range but is still in line of sight, it would go back into Approaching, etc.
