### ISSUE TITLE
RocketDog position messed up in Master?

### ISSUE THREAD

**Issue by zapyzappy** [sharris40/RocketDog#58]
I just cloned RocketDog master branch and RocketDog is being forced in the top left corner and the lasers are not following him correctly. Is anyone else having this problem?

**Comment by zapyzappy** [comment]
After looking around I finally figured out why it is not working. However I am still lost on why the Rocketdog sprite is not synced with where RocketDog's actual position is.

**Comment by tripledubs** [comment]
Level one? need to uncomment

```
    getSprite().setLayoutX(getPosition().getX());
    getSprite().setTranslateY(getPosition().getY());
    getHitbox().setLayoutX(getPosition().getX());
    getHitbox().setTranslateY(getPosition().getY());
```

lines 101-105 in Rocketdog..

Going to Command pattern Rocketdog would be moved by instantiating MoveRight or MoveLeft instead of in Update method
